# Generated by Django 2.0.13 on 2019-02-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nationality',
            field=models.CharField(max_length=15),
        ),
    ]
